### ISSUE TITLE
ISAD csv's

### ISSUE THREAD

**Issue by fneggers** [CCA-Public/cca-tools#5]
Our BitCurator environment (dedicated PC) accesses data on a network drive. BitCurator tools can access the data, but when the CCA tools execute an action, data are not processed and no result data are returned. Could this be a network problem (or a Bitcurator or network configuration problem)? Or should it be solved on the level of the CCA tools?

**Comment by fneggers** [comment]
Since the final installation of our dedicated BitCurator PC and the installation of the CCA tools about a year ago, the tools don't produce anymore the ISAD csv files. I tried to fix this by a re-installation of the CCA tools, but this dit not solve the problem.

**Comment by tw4l** [comment]
Resolved - see https://github.com/CCA-Public/cca-tools/issues/4
